[workspace]
members = [
    "./ft_token",
    "./nft_collection",
    "./proxy_token",
    "./nft_escrow",
]

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true